name: CI-CD

# Déclenche le workflow lors d'un push sur la branche main
on:
   push:
    branches:
      - main 

# Définition des jobs
jobs:
  build:
    # Système d'exploitation utilisé pour exécuter les actions
    runs-on: ubuntu-latest

    # Définition des étapes du job
    steps:
      # Récupération du code source
      - name: Checkout code
        uses: actions/checkout@v2

    # Installation de Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.11.0'

    # Installation des dépendances
      - name: Install dependencies
        run: npm install 

    # Build du projet Angular
      - name: Build Angular project
        run: npm run build --prod

    # Déploiement sur AWS Lightsail
      - name: Deploy to AWS Lightsail
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.LIGHTSAIL_SERVER_IP }}
          USERNAME: 'ubuntu'
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem

          scp -i private_key.pem -o StrictHostKeyChecking=no -r dist/jeuxolympiques/* $USERNAME@$SERVER_IP:/var/www/jeuxolympiques/

          ssh -i private_key.pem -o StrictHostKeyChecking=no $USERNAME@$SERVER_IP << 'EOF'
          cd /var/www/jeuxolympiques
          npm install --production
          sudo systemctl restart your-angular-app
          EOF